import React, { useState, useEffect } from 'react';
import {
  Shield,
  Users,
  QrCode,
  ShieldAlert,
  FileSpreadsheet,
  ShoppingBag,
  DollarSign,
  Building2,
  BarChart3,
  Settings,
  Download,
  Filter,
  Search,
  CheckCircle,
  Radio,
  MapPin,
  Phone,
  Navigation,
  Check,
  UserCheck,
  Lock,
  Unlock,
  AlertTriangle,
  RefreshCw
} from 'lucide-react';
import { SOSAlert, UserRole, QRCodeTag, ProductOrder, WalletTransaction } from '../../types';
import { SOSService } from '../../services/SOSService';
import { QRService } from '../../services/QRService';
import { OrderService } from '../../services/OrderService';
import { UserService } from '../../services/UserService';
import { useAuth } from '../../context/AuthContext';
import { UserManagement } from './UserManagement';

export const SuperAdminDashboard: React.FC = () => {
  const { userProfile, updateRole } = useAuth();
  const [activeTab, setActiveTab] = useState<
    | 'users'
    | 'qr'
    | 'sos'
    | 'incidents'
    | 'orders'
    | 'payments'
    | 'distributors'
    | 'analytics'
    | 'settings'
  >('sos');

  // SOS States
  const [alerts, setAlerts] = useState<SOSAlert[]>([]);
  const [statusFilter, setStatusFilter] = useState<'ALL' | 'ACTIVE' | 'DISPATCHED' | 'RESOLVED'>('ALL');

  // QR Tags States
  const [qrTags, setQrTags] = useState<QRCodeTag[]>([]);

  // Users States
  const [userSearch, setUserSearch] = useState('');
  const [userList, setUserList] = useState<
    Array<{ uid: string; name: string; email: string; role: UserRole; phone: string }>
  >([
    { uid: 'u1', name: 'Ramesh Sharma', email: 'ramesh@gmail.com', role: 'Customer', phone: '+91 9876543210' },
    { uid: 'u2', name: 'Dr. Anita Roy', email: 'anita@safelife.in', role: 'Emergency Responder', phone: '+91 9876543211' },
    { uid: 'u3', name: 'Salamat Sekh', email: 'salamatsekh405@gmail.com', role: 'Super Admin', phone: '+91 9876543212' },
    { uid: 'u4', name: 'Metro Safety Agencies', email: 'metro@distributor.in', role: 'Distributor', phone: '+91 9876543213' },
    { uid: 'u5', name: 'Kolkata Central Office', email: 'kolkata@safelife.in', role: 'Branch Admin', phone: '+91 9876543214' },
  ]);

  // Orders State
  const [orders, setOrders] = useState<ProductOrder[]>([
    {
      id: 'ORD_101',
      userId: 'u1',
      productName: 'Emergency Helmet & Bike QR Sticker Pack (Set of 3)',
      quantity: 2,
      totalAmount: 598,
      status: 'PENDING',
      shippingAddress: 'Flat 4B, Salt Lake Sector 5, Kolkata, WB 700091',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'ORD_102',
      userId: 'u1',
      productName: 'Senior Citizen Medical Alert Smart Tag',
      quantity: 1,
      totalAmount: 499,
      status: 'DISPATCHED',
      shippingAddress: 'Park Street 12, Kolkata, WB 700016',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    }
  ]);

  // System Settings State
  const [smsGatewayActive, setSmsGatewayActive] = useState(true);
  const [maintenanceMode, setMaintenanceMode] = useState(false);
  const [nationalHelpline, setNationalHelpline] = useState('112');

  useEffect(() => {
    const unsubSOS = SOSService.subscribeActiveAlerts((data) => setAlerts(data));
    const unsubQR = QRService.subscribeAllTags((data) => setQrTags(data));
    return () => {
      unsubSOS();
      unsubQR();
    };
  }, []);

  const activeCases = alerts.filter((a) => a.status === 'ACTIVE').length;
  const dispatchedCases = alerts.filter((a) => a.status === 'DISPATCHED').length;
  const resolvedCases = alerts.filter((a) => a.status === 'RESOLVED').length;

  const handleDispatch = async (alertId: string) => {
    const unit = prompt('Enter Dispatch Unit / Responder Name:', 'Ambulance 108 - Rapid Unit 04');
    if (!unit) return;
    try {
      await SOSService.updateStatus(alertId, 'DISPATCHED', `Dispatched Unit: ${unit}`);
    } catch (err) {
      console.error('Dispatch error:', err);
    }
  };

  const handleResolve = async (alertId: string) => {
    const notes = prompt('Enter Case Resolution Summary / Notes:', 'Victim safely assisted on scene by emergency team.');
    try {
      await SOSService.updateStatus(alertId, 'RESOLVED', notes || 'Case closed safely.');
    } catch (err) {
      console.error('Resolve error:', err);
    }
  };

  const exportReport = (reportType: string) => {
    let content = `========================================================\n`;
    content += `SAFE LIFE SUPER ADMIN PLATFORM AUDIT REPORT\n`;
    content += `Report Type: ${reportType}\n`;
    content += `Generated By: ${userProfile?.fullName || 'Super Admin'}\n`;
    content += `Timestamp: ${new Date().toLocaleString()}\n`;
    content += `========================================================\n\n`;
    content += `SUMMARY METRICS:\n`;
    content += `- Total SOS Cases: ${alerts.length}\n`;
    content += `- Active SOS Alerts: ${activeCases}\n`;
    content += `- Dispatched Responders: ${dispatchedCases}\n`;
    content += `- Resolved Emergency Cases: ${resolvedCases}\n`;
    content += `- Total Registered QR Tags: ${qrTags.length}\n\n`;
    content += `DETAILED INCIDENT LOGS:\n`;
    alerts.forEach((a, index) => {
      content += `${index + 1}. [ID: ${a.id}] [Status: ${a.status}] [Type: ${a.alertType}]\n`;
      content += `   Victim Name: ${a.userName} | Phone: ${a.userPhone}\n`;
      content += `   Address: ${a.address}\n`;
      content += `   Coordinates: Lat ${a.latitude}, Lng ${a.longitude}\n`;
      content += `   Created: ${new Date(a.createdAt).toLocaleString()}\n`;
      if (a.responderNotes) content += `   Notes: ${a.responderNotes}\n`;
      content += `--------------------------------------------------------\n`;
    });

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SuperAdmin_Audit_${Date.now()}.txt`;
    a.click();
  };

  const filteredUsers = userList.filter(
    (u) =>
      u.name.toLowerCase().includes(userSearch.toLowerCase()) ||
      u.email.toLowerCase().includes(userSearch.toLowerCase()) ||
      u.role.toLowerCase().includes(userSearch.toLowerCase())
  );

  const adminTabs: Array<{ id: string; label: string; icon: any; badge?: number }> = [
    { id: 'sos', label: 'SOS Monitoring', icon: ShieldAlert, badge: activeCases },
    { id: 'users', label: 'User Management', icon: Users },
    { id: 'qr', label: 'QR Management', icon: QrCode },
    { id: 'incidents', label: 'Incident Reports', icon: FileSpreadsheet },
    { id: 'orders', label: 'Orders', icon: ShoppingBag },
    { id: 'payments', label: 'Payments & Wallet', icon: DollarSign },
    { id: 'distributors', label: 'Distributors', icon: Building2 },
    { id: 'analytics', label: 'Analytics', icon: BarChart3 },
    { id: 'settings', label: 'System Settings', icon: Settings },
  ];

  return (
    <div className="space-y-6">
      {/* Super Admin Top Header */}
      <div className="bg-gradient-to-r from-slate-900 via-blue-950 to-slate-900 border border-slate-800 rounded-2xl p-6 text-white shadow-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 mb-1">
            <Shield className="w-5 h-5 text-yellow-400" />
            <span className="bg-yellow-400 text-slate-950 text-[10px] font-black px-2 py-0.5 rounded uppercase">
              Super Admin Command
            </span>
            <span className="text-xs text-blue-300 font-mono">National Platform Operations</span>
          </div>
          <h1 className="text-2xl font-black tracking-tight text-white">Full Platform Command Center</h1>
          <p className="text-xs text-slate-300 mt-1 max-w-2xl">
            Complete platform administrative control: user roles, QR tags, live emergency dispatch monitoring, incident audit logs, order fulfillment, and system gateways.
          </p>
        </div>

        <button
          onClick={() => exportReport('Platform Audit Summary')}
          className="bg-yellow-400 hover:bg-yellow-300 text-slate-950 text-xs font-black px-4 py-2.5 rounded-xl flex items-center space-x-2 shadow-lg transition active:scale-95 shrink-0"
        >
          <Download className="w-4 h-4 text-slate-950" />
          <span>Export Audit Log</span>
        </button>
      </div>

      {/* Admin Tab Navigation Bar */}
      <div className="flex overflow-x-auto bg-white p-2 rounded-2xl border border-slate-200 shadow-md space-x-1 scrollbar-none">
        {adminTabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center space-x-1.5 px-3.5 py-2 rounded-xl text-xs font-bold transition whitespace-nowrap shrink-0 ${
                isActive
                  ? 'bg-slate-900 text-yellow-400 shadow-md font-extrabold'
                  : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
              {tab.badge !== undefined && tab.badge > 0 && (
                <span className="bg-red-600 text-white text-[10px] font-black px-1.5 py-0.2 rounded-full animate-pulse">
                  {tab.badge}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* TAB 1: SOS MONITORING */}
      {activeTab === 'sos' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div>
              <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
                <ShieldAlert className="w-5 h-5 text-red-600 animate-pulse" />
                <span>Live SOS Monitoring Stream</span>
              </h2>
              <p className="text-xs text-slate-500">Real-time distress signals from all nationwide users.</p>
            </div>

            <div className="flex items-center space-x-2">
              {(['ALL', 'ACTIVE', 'DISPATCHED', 'RESOLVED'] as const).map((st) => (
                <button
                  key={st}
                  onClick={() => setStatusFilter(st)}
                  className={`px-3 py-1 rounded-lg text-xs font-bold transition ${
                    statusFilter === st ? 'bg-red-600 text-white shadow' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                  }`}
                >
                  {st}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-4">
            {alerts.length === 0 ? (
              <div className="text-center py-12 bg-slate-50 border-2 border-dashed border-slate-200 rounded-2xl text-slate-500 text-xs font-medium">
                No emergency SOS cases registered in system.
              </div>
            ) : (
              alerts.map((al) => (
                <div
                  key={al.id}
                  className={`p-4 rounded-xl border flex flex-col md:flex-row md:items-center justify-between gap-4 ${
                    al.status === 'ACTIVE'
                      ? 'bg-red-50 border-red-300'
                      : al.status === 'DISPATCHED'
                      ? 'bg-yellow-50 border-yellow-300'
                      : 'bg-slate-50 border-slate-200'
                  }`}
                >
                  <div>
                    <div className="flex items-center space-x-2">
                      <span className={`text-[10px] font-black px-2 py-0.5 rounded ${
                        al.status === 'ACTIVE' ? 'bg-red-600 text-white' : 'bg-yellow-400 text-slate-950'
                      }`}>
                        {al.status}
                      </span>
                      <span className="text-xs font-bold text-slate-800">{al.userName}</span>
                      <span className="text-xs text-slate-500">({al.userPhone})</span>
                    </div>
                    <div className="text-xs text-slate-700 mt-1 font-mono">{al.address}</div>
                    <div className="text-[10px] text-slate-400 mt-1">{new Date(al.createdAt).toLocaleString()}</div>
                  </div>

                  <div className="flex items-center space-x-2 shrink-0">
                    <a
                      href={`https://www.google.com/maps/dir/?api=1&destination=${al.latitude},${al.longitude}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="bg-blue-600 text-white text-xs font-bold px-3 py-1.5 rounded-lg flex items-center space-x-1"
                    >
                      <Navigation className="w-3.5 h-3.5" />
                      <span>GPS</span>
                    </a>
                    {al.status === 'ACTIVE' && (
                      <button
                        onClick={() => handleDispatch(al.id)}
                        className="bg-yellow-400 text-slate-950 text-xs font-bold px-3 py-1.5 rounded-lg"
                      >
                        Dispatch
                      </button>
                    )}
                    {al.status !== 'RESOLVED' && (
                      <button
                        onClick={() => handleResolve(al.id)}
                        className="bg-green-600 text-white text-xs font-bold px-3 py-1.5 rounded-lg"
                      >
                        Resolve
                      </button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      )}

      {/* TAB 2: USER MANAGEMENT */}
      {activeTab === 'users' && <UserManagement />}

      {/* TAB 3: QR MANAGEMENT */}
      {activeTab === 'qr' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="border-b border-slate-100 pb-4">
            <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
              <QrCode className="w-5 h-5 text-blue-600" />
              <span>System QR Tags Directory</span>
            </h2>
            <p className="text-xs text-slate-500">Monitor all registered emergency QR stickers and tags across India.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="text-xs font-bold text-slate-500">Total QR Tags</div>
              <div className="text-2xl font-black text-slate-900 mt-1">{qrTags.length}</div>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="text-xs font-bold text-slate-500">Active Tags</div>
              <div className="text-2xl font-black text-green-600 mt-1">{qrTags.filter(t => t.isActive).length}</div>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="text-xs font-bold text-slate-500">Deactivated Tags</div>
              <div className="text-2xl font-black text-red-600 mt-1">{qrTags.filter(t => !t.isActive).length}</div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: INCIDENT REPORTS */}
      {activeTab === 'incidents' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="flex items-center justify-between border-b border-slate-100 pb-4">
            <div>
              <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
                <FileSpreadsheet className="w-5 h-5 text-blue-600" />
                <span>Incident Reports & Audit Summary</span>
              </h2>
              <p className="text-xs text-slate-500">Download system incident reports for official emergency audit.</p>
            </div>
            <button
              onClick={() => exportReport('Incident History Log')}
              className="bg-blue-600 text-white text-xs font-bold px-3.5 py-2 rounded-xl flex items-center space-x-1.5"
            >
              <Download className="w-4 h-4" />
              <span>Download Report</span>
            </button>
          </div>

          <div className="space-y-3 text-xs">
            {alerts.map((al) => (
              <div key={al.id} className="p-3 bg-slate-50 rounded-xl border border-slate-200 flex justify-between">
                <div>
                  <span className="font-bold">{al.userName}</span> ({al.alertType}) - {al.address}
                </div>
                <span className="font-bold text-blue-600">{al.status}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 5: ORDERS */}
      {activeTab === 'orders' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="border-b border-slate-100 pb-4">
            <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
              <ShoppingBag className="w-5 h-5 text-blue-600" />
              <span>Safety Product Orders & Fulfillment</span>
            </h2>
            <p className="text-xs text-slate-500">Track and dispatch customer orders for QR tags and emergency kits.</p>
          </div>

          <div className="space-y-3 text-xs">
            {orders.map((ord) => (
              <div key={ord.id} className="p-4 bg-slate-50 rounded-xl border border-slate-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <div>
                  <div className="font-bold text-slate-900">{ord.productName} (x{ord.quantity}) - ₹{ord.totalAmount}</div>
                  <div className="text-[11px] text-slate-500">{ord.shippingAddress}</div>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="bg-yellow-100 text-yellow-800 font-bold px-2 py-0.5 rounded text-[10px]">{ord.status}</span>
                  <button
                    onClick={() => {
                      setOrders(prev => prev.map(o => o.id === ord.id ? { ...o, status: 'DISPATCHED' } : o));
                    }}
                    className="bg-blue-600 text-white font-bold px-2.5 py-1 rounded-lg text-[10px]"
                  >
                    Mark Dispatched
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 6: PAYMENTS & WALLET */}
      {activeTab === 'payments' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="border-b border-slate-100 pb-4">
            <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
              <DollarSign className="w-5 h-5 text-blue-600" />
              <span>Payments, Wallet & Revenue Metrics</span>
            </h2>
            <p className="text-xs text-slate-500">Monitor digital wallet transactions, Razorpay/UPI topups, and distributor commissions.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="text-xs font-bold text-slate-500">Total System Revenue</div>
              <div className="text-2xl font-black text-slate-900 mt-1">₹1,24,500</div>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="text-xs font-bold text-slate-500">Wallet Credits</div>
              <div className="text-2xl font-black text-green-600 mt-1">₹45,000</div>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <div className="text-xs font-bold text-slate-500">Distributor Payouts</div>
              <div className="text-2xl font-black text-blue-600 mt-1">₹18,000</div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 7: DISTRIBUTORS */}
      {activeTab === 'distributors' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="border-b border-slate-100 pb-4">
            <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
              <Building2 className="w-5 h-5 text-blue-600" />
              <span>Distributor Network & Franchise Allocation</span>
            </h2>
            <p className="text-xs text-slate-500">Manage offline QR tag distributors and regional partners.</p>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2 text-xs">
            <div className="font-bold text-slate-900">Metro Safety Agencies (District Distributor)</div>
            <p className="text-slate-600">Assigned Region: Kolkata Central & Howrah | QR Batch Allocated: 1,000 Tags</p>
          </div>
        </div>
      )}

      {/* TAB 8: ANALYTICS */}
      {activeTab === 'analytics' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="border-b border-slate-100 pb-4">
            <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
              <BarChart3 className="w-5 h-5 text-blue-600" />
              <span>Platform Analytics & Emergency Response Metrics</span>
            </h2>
            <p className="text-xs text-slate-500">Performance graphs and emergency response time statistics.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 bg-blue-50 rounded-xl border border-blue-200 text-xs">
              <div className="font-bold text-blue-900">Average Emergency Response Time</div>
              <div className="text-3xl font-black text-blue-700 mt-2">4.2 Minutes</div>
            </div>
            <div className="p-4 bg-green-50 rounded-xl border border-green-200 text-xs">
              <div className="font-bold text-green-900">Successful SOS Assistance Rate</div>
              <div className="text-3xl font-black text-green-700 mt-2">99.4%</div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 9: SYSTEM SETTINGS */}
      {activeTab === 'settings' && (
        <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xl space-y-6 text-slate-900">
          <div className="border-b border-slate-100 pb-4">
            <h2 className="text-lg font-bold text-slate-900 flex items-center space-x-2">
              <Settings className="w-5 h-5 text-blue-600" />
              <span>System Configuration & Operational Gateways</span>
            </h2>
            <p className="text-xs text-slate-500">Configure national emergency hotline routing and SMS broadcast switches.</p>
          </div>

          <div className="space-y-4 max-w-lg">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">National Helpline Number</label>
              <input
                type="text"
                value={nationalHelpline}
                onChange={(e) => setNationalHelpline(e.target.value)}
                className="w-full border border-slate-300 rounded-xl px-3 py-2 text-xs focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs">
              <div>
                <div className="font-bold text-slate-800">SMS / WhatsApp Emergency Broadcast Gateway</div>
                <div className="text-[10px] text-slate-500">Automatically send SMS alerts to emergency contacts</div>
              </div>
              <input
                type="checkbox"
                checked={smsGatewayActive}
                onChange={(e) => setSmsGatewayActive(e.target.checked)}
                className="w-4 h-4 text-blue-600 rounded"
              />
            </div>

            <div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs">
              <div>
                <div className="font-bold text-slate-800">System Maintenance Mode</div>
                <div className="text-[10px] text-slate-500">Restrict user profile updates during scheduled maintenance</div>
              </div>
              <input
                type="checkbox"
                checked={maintenanceMode}
                onChange={(e) => setMaintenanceMode(e.target.checked)}
                className="w-4 h-4 text-blue-600 rounded"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
